# Generated by Django 2.2.5 on 2019-12-07 00:10
import json
from django.db import migrations


def create_genre(genres, Model):
    genres = (genre.strip() for genre in genres.split(","))

    for genre in genres:
        genre, _ = Model.objects.get_or_create(name=genre)
        yield genre


def delete_all_music_data(apps, schema_editor):
    Artist = apps.get_model("music", "Artist")
    Genre = apps.get_model("music", "Genre")

    Artist.objects.all().delete()
    Genre.objects.all().delete()


def import_data_from_json(apps, schema_editor):
    Artist = apps.get_model("music", "Artist")
    Genre = apps.get_model("music", "Genre")

    with open("./music/migrations/data/spotify-artists.json", "r") as f:
        artists = json.load(f)
        for artist in artists:
            genres = create_genre(artist.get("genres", ""), Genre)

            artist, _ = Artist.objects.get_or_create(
                name=artist.get("name"),
                spotify_url=artist.get("artistLink"),
                picture=artist.get("picture", ""),
            )

            for genre in genres:
                artist.related_genres.add(genre, bulk=True)

            artist.save()


class Migration(migrations.Migration):

    dependencies = [("music", "0002_auto_20191207_0010")]

    operations = [migrations.RunPython(import_data_from_json, delete_all_music_data)]
