# Generated by Django 2.2.5 on 2019-12-07 00:47

import json
from django.db import migrations


def delete_all_tidal_urls(apps, schema_editor):
    Artist = apps.get_model("music", "Artist")

    for artist in Artist.objects.all():
        artist.tidal_url = ""
        artist.save()


def import_data_from_json(apps, schema_editor):
    Artist = apps.get_model("music", "Artist")

    with open("./music/migrations/data/tidal-artists.json", "r") as f:
        artists = json.load(f)
        for artist in artists:
            art = Artist.objects.filter(name=artist.get("name")).first()

            if art:
                art.tidal_url = artist.get("artistLink", "")
                art.save()
            else:
                Artist(
                    **{
                        "name": artist.get("name"),
                        "tidal_url": artist.get("artistLink"),
                        "picture": artist.get("picture", ""),
                    }
                ).save()


class Migration(migrations.Migration):

    dependencies = [("music", "0003_auto_20191207_0010")]

    operations = [migrations.RunPython(import_data_from_json, delete_all_tidal_urls)]
